apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: k8s-obs-stack
  labels:
    app: promtail
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      # Ensure this URL points to the Loki service
      - url: http://loki-gateway.loki.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
    - job_name: kubernetes-pods-app-logs
      kubernetes_sd_configs:
        - role: pod
      
      # Relabeling ensures logs get the same labels as Prometheus metrics
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: app
        - source_labels: [__meta_kubernetes_container_name]
          target_label: container

        # Drop system logs
        - action: drop
          regex: (?:kube-system|monitoring|logging)/.+
          source_labels:
            [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_k8s_app]

      pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
          drop_key: true
          source_key: message