apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-observability-stack.fullname" . }}
  labels:
    {{- include "k8s-observability-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.microservice.service.type }}
  ports:
    - port: {{ .Values.microservice.service.port }}
      targetPort: {{ .Values.microservice.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-observability-stack.selectorLabels" . | nindent 4 }}